[package]
name = "TuiWeather"
version = "0.0.3"
edition = "2024"

[dependencies]
serde = {version = "1.0.228", features = ["derive"]}
reqwest = {version = "0.13.2",features = ["json"]}
tokio = {version = "1.49.0",features = ["full"]}